let suratNames=["startsuratNames",

"الفاتحة (Al-Fatihah) - The Opening",
"2. البقرة (Al-Baqarah) - The Cow",
"3. آل عمران (Aal-E-Imran) - The Family of Imran",
"4. النساء (An-Nisa') - The Women",
"5. المائدة (Al-Ma'idah) - The Table Spread",
"6. الأنعام (Al-An'am) - The Cattle",
"7. الأعراف (Al-A'raf) - The Heights",
"8. الأنفال (Al-Anfal) - The Spoils of War",
"9. التوبة (At-Tawbah) - The Repentance",
"10. يونس (Yunus) - Jonah",
"11. هود (Hud) - Hud",
"12. يوسف (Yusuf) - Joseph",
"13. الرعد (Ar-Ra'd) - The Thunder",
"14. إبراهيم (Ibrahim) - Abraham",
"15. الحجر (Al-Hijr) - The Rocky Tract",
"16. النحل (An-Nahl) - The Bee",
"17. الإسراء (Al-Isra') - The Night Journey",
"18. الكهف (Al-Kahf) - The Cave",
"19. مريم (Maryam) - Mary",
"20. طه (Ta-Ha) - Ta-Ha",
"21. الأنبياء (Al-Anbiya') - The Prophets",
"22. الحج (Al-Hajj) - The Pilgrimage",
"23. المؤمنون (Al-Mu'minun) - The Believers",
"24. النور (An-Nur) - The Light",
"25. الفرقان (Al-Furqan) - The Criterion",
"26. الشعراء (Ash-Shu'ara') - The Poets",
"27. النمل (An-Naml) - The Ant",
"28. القصص (Al-Qasas) - The Stories",
"29. العنكبوت (Al-Ankabut) - The Spider",
"30. الروم (Ar-Rum) - The Romans",
"31. لقمان (Luqman) - Luqman",
"32. السجدة (As-Sajda) - The Prostration",
"33. الأحزاب (Al-Ahzab) - The Confederates",
"34. سبأ (Saba) - Sheba",
"35. فاطر (Fatir) - The Originator",
"36. يس (Ya-Sin) - Ya-Sin",
"37. الصافات (As-Saffat) - Those who set the Ranks",
"38. ص (Sad) - The Letter Sad",
"39. الزمر (Az-Zumar) - The Groups",
"40. غافر (Ghafir) - The Forgiver",
"41. فصلت (Fussilat) - Explained in Detail",
"42. الشورى (Ash-Shura) - The Consultation",
"43. الزخرف (Az-Zukhruf) - The Gold Adornments",
"44. الدخان (Ad-Dukhan) - The Smoke",
"45. الجاثية (Al-Jathiya) - The Crouching",
"46. الأحقاف (Al-Ahqaf) - The Wind-Curved Sandhills",
"47. محمد (Muhammad) - Muhammad",
"48. الفتح (Al-Fath) - The Victory",
"49. الحشر (Al-Hashr) - The Exile",
"50. الممتحنة (Al-Mumtahina) - She that is to be examined",
"51. الصف (As-Saff) - The Ranks",
"52. الطور (Ad-Dhariyat) - The Mount",
"53. النجم (An-Najm) - The Star",
"54. القمر (Al-Qamar) - The Moon"<
"55. الرحمن (Ar-Rahman) - The Beneficent",
"56. الواقعة (Al-Waqi'a) - The Inevitable",
"57. الحديد (Al-Hadid) - The Iron",
"58. المجادلة (Al-Mujadila) - The Pleading Woman",
"59. الحشر (Al-Hashr) - The Gathering",
"60. الممتحنة (Al-Mumtahina) - She that is to be examined",
"61. الصف (As-Saff) - The Ranks",
"62. الجمعة (Al-Jumu'a) - The Congregation",
"63. المنافقون (Al-Munafiqun) - The Hypocrites",
"64. التغابن (At-Taghabun) - The Mutual Disillusion",
"65. الطلاق (At-Talaq) - The Divorce",
"66. التحريم (At-Tahrim) - The Prohibition",
"67. الملك (Al-Mulk) - The Sovereignty",
"68. القلم (Al-Qalam) - The Pen",
"69. الحاقة (Al-Haaqqa) - The Reality",
"70. المعارج (Al-Ma'arij) - The Ascending Stairways",
"71. نوح (Nuh) - Noah",
"72. الجن (Al-Jinn) - The Jinn",
"73. المزمل (Al-Muzzammil) - The Enshrouded One",
"74. المدثر (Al-Muddathir) - The Cloaked One",
"75. القيامة (Al-Qiyama) - The Resurrection",
"76. الإنسان (Al-Insan) - Man",
"77. المرسلات (Al-Mursalat) - The Emissaries",
"78. النبأ (An-Naba') - The Tidings",
"79. النازعات (An-Nazi'at) - Those who drag forth",
"80. عبس (Abasa) - He frowned",
"81. التكوير (At-Takwir) - The Overthrowing",
"82. الإنفطار (Al-Infitar) - The Cleaving",
"83. المطففين (Al-Mutaffifin) - The Defrauding",
"84. الإنشقاق (Al-Inshiqaq) - The Splitting Open",
"85. البروج (Al-Buruj) - The Mansions of the Stars",
"86. الطارق (At-Tariq) - The Morning Star",
"87. الأعلى (Al-Ala) - The Most High",
"88. الغاشية (Al-Ghashiyah)",

"89. الفجر (Al-Fajr) - The Dawn",
"90. البلد (Al-Balad) - The City",
"91. الشمس (Ash-Shams) - The Sun",
"92. الليل (Al-Layl) - The Night",
"93. الضحى (Ad-Duha) - The Morning Hours",
"94. الشرح (Ash-Sharh) - The Relief",
"95. التين (At-Tin) - The Fig",
"96. العلق (Al-Alaq) - The Clot",
"97. القدر (Al-Qadr) - The Power",
"98. البينة (Al-Bayyina) - The Clear Proof",
"99. الزلزلة (Az-Zalzalah) - The Earthquake",
"100. العاديات (Al-Adiyat) - The Chargers",
"101. القارعة (Al-Qari'a) - The Calamity",
"102. التكاثر (At-Takathur) - The Rivalry in Worldly Increase",
"103. العصر (Al-Asr) - The Declining Day",
"104. الهمزة (Al-Humazah) - The Traducer",
"105. الفيل (Al-Fil) - The Elephant",
"106. قريش (Quraish) - Quraish",
"107. الماعون (Al-Ma'un) - Small Kindnesses",
"108. الكوثر (Al-Kawthar) - The Abundance",
"109. الكافرون (Al-Kafirun) - The Disbelievers",
"110. النصر (An-Nasr) - The Divine Support",
"111. المسد (Al-Masad) - The Palm Fiber",
"112. الإخلاص (Al-Ikhlas) - Sincerity",
"113. الفلق (Al-Falaq) - The Daybreak",
"114. الناس (An-Nas) - Mankind",
];
function surats(){
    let suratprint= " "
    // document.getElementById('suratprint').innerHTML=suratNames
    for (let i =0 ; i< suratNames.length; i++) {
    
        document.getElementById('suratprint').innerHTML+= suratNames[i] + "<br>"

    }
    
    }

function suratinput(){
    
    let suratprint1=" "

suratnum= parseInt (document.getElementById('inputnum').value)

document.getElementById('suratprint1').innerHTML=suratNames[suratnum]

}

